### ISSUE TITLE
[BUG] Incompatability with package dependence

### ISSUE THREAD

**Issue by jdsouz** [gretelai/gretel-synthetics#118]
**Are you reporting a bug or FR?**
 - [ x] Bug

**What version of synthetics are you using?**

v0.17.0

**What would you like to see / What problem are you having?**

<img width="1624" alt="Screen Shot 2022-04-27 at 9 31 04 PM" src="https://user-images.githubusercontent.com/52765986/165658347-6161e6b4-63cc-4315-8f17-5feb597c700b.png">

I am wondering if you have any idea of where this error is coming from and if this versioning warning poses any issue for the functionality of the code.

**Configuration Params**

Unsure

**Are you using GPU or a CPU?**

CPU

**What environment are you working in?**

Google Colab on the drive (not locally

**What version of python are you using?**

3.7

**Describe the shape / types of the data you are training on**

Netflix Prize Data

<DataFrame dimensions, what type of data in the columns, etc>

24053764 x 4, without headings.

**Please provide any tracebacks or error messages you are receiving**
Please see above

**Comment by johntmyers** [comment]
@jdsouz are you able to re-install `tensorflow==2.4.0` via `!pip install -U tensorflow==2.4.0` ... for some reason it looks like the RC1 of TF was installed?

**Comment by johntmyers** [comment]
@jdsouz Since we have not heard back, I am going to close this issue.
