### ISSUE TITLE
TooManyInvalidError: Maximum number of invalid lines reached!

### ISSUE THREAD

**Issue by FirasNacef** [gretelai/gretel-synthetics#131]
Hello, 

I am trying to generate new lines for my dataframe which contains survey responses (So categorical variables that are not yet encoded). I ran the "synthetic_records" notebook hoping that it would create new responses that are similar but not identical to the ones already existing. When training, the RNN reached 91% accuracy, but when running the lines generating code the output kept giving me a list of lines in this format : 

GenText(valid=False, text ="value1,value2,value3,etc...", explain='record not 6 parts', delimiter=',')

Here's the error message I got :

![image](https://user-images.githubusercontent.com/101456672/195639383-7b3644af-5e86-4e33-95ee-128848db56ec.png)

**Comment by johntmyers** [comment]
Hi @FirasNacef can you share more of the full traceback? Also this error usually means that the model cannot generate the expected number of columns, which could stem from a variety of issues like sparse columns. If you can share your dataset that would be helpful too.

**Comment by FirasNacef** [comment]
[poll3.csv](https://github.com/gretelai/gretel-synthetics/files/9778447/poll3.csv)

You will find attached the dataset I used.

**Comment by zredlined** [comment]
Hey @FirasNacef - try running ACTGAN, it should work just fine for your dataset (the LSTM model you were using needed more examples to learn the structure and format). 

https://github.com/gretelai/gretel-synthetics/blob/master/examples/ACTGAN_Demo.ipynb
