### ISSUE TITLE
[FR] Generation based on given attributes

### ISSUE THREAD

**Issue by jankrans** [gretelai/gretel-synthetics#135]
Hi,

I wondered if it is already possible to generate synthetic data based on given values from attributes? I remember that the original paper allows this?

Otherwise I might further look into this to implement it myself

Kind regards!

**Comment by kboyd** [comment]
Hi @jankrans, this is regarding our DGAN implementation, right?

DGAN does not currently support conditional generation from given attributes. You're exactly right that the DoppelGANger paper does include support for this though. Conditional generation is on our roadmap for DGAN, but we don't have a timeline yet.

We'd be happy to review a PR if you want to implement it yourself.

**Comment by DanielDimanov** [comment]
Any updates on this?
