### ISSUE TITLE
[FR / BUG]

### ISSUE THREAD

**Issue by AliKHaliliT** [gretelai/gretel-synthetics#137]
**Are you reporting a bug or FR?**
 - [*] Feature Request

**What version of synthetics are you using?**

 0.19.0

**What would you like to see / What problem are you having?**

 An evaluation module is highly required

<describe the FR or bug you are encountering>

 It is both hard and confusing to compare the correlation of the real data against the synthetic data. 
 This is a very straightforward and easy-to-use library thus it makes it possible for everyone to use it whether they have a solid 
 statistical and ML background or not. So availability of an evaluation module is highly required because most people can't trust the synthetic data that they create using this library because they lack the technical ability to correctly evaluate the data.

**Configuration Params**

 -----------------------------------------------------------------------------------

**Are you using GPU or a CPU?**

GPU

**What environment are you working in?**

Google Colab

**What version of python are you using?**

3.8

**Describe the shape / types of the data you are training on**

 TimeSeries

**Please provide any tracebacks or error messages you are receiving**

 -----------------------------------------------------------------------------------

**Comment by zredlined** [comment]
Thanks for reaching out @AliKHaliliT. We have a score for evaluating synthetic model quality vs real world data available as part of our cloud service, but it is not source-available at this time. You can read more about how [SQS works in our docs.](https://docs.gretel.ai/reference/synthetics/gretel-synthetic-report)

**Comment by AliKHaliliT** [comment]
Thank you for the response. 
I am closing this issue.
