### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by vinay-k12** [gretelai/gretel-synthetics#140]
**Are you reporting a bug or FR?**
 - Bug

I'm trying to import ACTGAN but I'm facing this error! 

"No module named 'rdt'"

How come I'm unable to load the library. 

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/19322429/214922768-3ed62da0-0d27-400f-8c98-60914a19cfc6.png">

**Comment by johntmyers** [comment]
Hi @vinay-k12 - for this model we ask users to install SDV themselves separately in order to avoid dependency conflicts with our other models. Have you done that? You can try: `pip install "sdv<0.18.0"` then re-starting the Notebook?

**Comment by vinay-k12** [comment]
Hey @johntmyers Yes. Installed 

!pip install tensorflow==2.8 
!pip install sdv==0.16.0
!pip install torch==1.13.1 

and !pip install gretel-synthetics

**Comment by johntmyers** [comment]
You don't need all three. Please check the README, you only need to install SDV and the version you installed may not be compatible as we rely on 0.17.x.

**Comment by vinay-k12** [comment]
This worked when I use SDV 0.17.0. It'd be nice if this is mentioned as well.

**Comment by johntmyers** [comment]
Glad it worked. For future reference, our version recommendations are on the readme: 

https://github.com/gretelai/gretel-synthetics#dependency-requirements
