### ISSUE TITLE
[BUG] : Loading a trained model and generating synthetic data throws an error

### ISSUE THREAD

**Issue by AravAct** [gretelai/gretel-synthetics#144]
**Are you reporting a bug or FR?**
 - [x] Bug
 - [ ] Feature Request

**What version of synthetics are you using?**
0.20.0

**What problem are you having?**
I am training a Timeseries DGAN model using the timeseries code provided by Gretel-synthetics library.
I have trained the model and saved it using model. Save(path) provided in the dgan.py file. I am trying to load the file using load function in the same dgan.py. Aftaer loading trying to generate synthetic data using generate_numpy()
It fails with Attribute error 'DGAN' object has no attribute 'attribute_noise_func'

**Configuration Params**

max_sequence_len=2000,
sample_len=1,
batch_size=128,
epochs=1000, # For real data sets, 100–1000 epochs is typical
  feature_num_layers=5,
  attribute_discriminator_learning_rate = 0.001,
feature_num_units = 100 ,
generator_learning_rate = 0.001 ,
    discriminator_learning_rate= 0.001

**Are you using GPU or a CPU?**
GPU

**What environment are you working in?**

Tried in both Jupyter & Google Colab, got the same error

**What version of python are you using?**

Tried in bth 3.8 (Colab)& 3.9(Jupyter)

**Describe the shape / types of the data you are training on**
(42000,31)
**Please provide any tracebacks or error messages you are receiving**
```
  471                 internal_data_list.append(
    472                     self._generate(self.attribute_noise_func(self.config.batch_size),
--> 473                                    self.feature_noise_func(self.config.batch_size),))
    474 
    475             # Convert from list of tuples to tuple of lists with zip(*) and

AttributeError: 'DGAN' object has no attribute 'attribute_noise_func'
```

**Comment by AravAct** [comment]
Error resolved with updating gretel-synthetics

**Comment by AravAct** [comment]
Reopened as error persists. Loading  a model and generating new data is not working.

**Comment by santhosh97** [comment]
Hey @AravAct ! Hope you're doing well! Do you mind sharing a snippet of what your input data looks like?

**Comment by AravAct** [comment]
Hi @santhosh97 ,
Thanks for the reply. 
Although I cannot share the data directly, I can share the shape of the dataset. We have transformed the data to required format( wide format) for the model.
Shape of the data is  (21, 2000, 6)
21 unique timeseries sequences, of length 2000 each and 6 features. We do not have any categorical variables, all are numerical.

**Comment by kboyd** [comment]
We're not able to reproduce that error after loading a model yet to investigate further. @AravAct can you share a minimum chunk of code that produces the error? So the model create, train, save, load, and generate code that leads to the error. I don't expect the exact data is the issue here based on the error, so I'm hoping random data (e.g., `np.random.random(21, 6000, 6)`) will still reproduce the problem so you can share some code that doesn't rely on your data directly.

**Comment by kboyd** [comment]
The only way I've found to generate the error is to run `generate_dataframe` (or `generate_numpy`) immediately after making the DGAN instance, before training:

```
from gretel_synthetics.timeseries_dgan.config import DGANConfig
from gretel_synthetics.timeseries_dgan.dgan import DGAN
dg = DGAN(DGANConfig(max_sequence_len=2000, sample_len=1))
dg.generate_numpy(n=3)
```
Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kendrick/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gretel_synthetics/timeseries_dgan/dgan.py", line 436, in generate_numpy
    self.attribute_noise_func(self.config.batch_size),
AttributeError: 'DGAN' object has no attribute 'attribute_noise_func'
```

We can definitely provide a clearer error message in this situation. But this seems unrelated to saving and loading a model, so probably not helpful for this bug.

**Comment by AravAct** [comment]
I tried the suggested, adding DGAN instance before loading the model. Below is a reproducible code. Kindly let me know if I am making a mistake or this is something else.

```
run_ = 'Doppelganger_exp_savedmodel'
file_name_model = str(run_)+'.pt'

timelength = 2000
sample_len_=1
batch_size_=500
epochs_=30
num_layers_=2
num_units_ = 30
adlr_= 0.8
glr_=0.8
dlr_=0.8

features = np.random.rand(21, 2000, 6)
attributes = np.random.rand(21,1)
# Train the model
model = DGAN(DGANConfig(
    max_sequence_len=timelength,
    sample_len=sample_len_,
    batch_size=batch_size_,
    epochs=epochs_, # For real data sets, 100–1000 epochs is typical
     feature_num_layers=num_layers_,
     attribute_discriminator_learning_rate = adlr_,
    feature_num_units = num_units_ ,
    generator_learning_rate = glr_ ,
        discriminator_learning_rate= dlr_,
))

model.train_numpy(
      # run = run_,
      attributes=attributes,
      attribute_types = [OutputType.DISCRETE] * 1,
      features=features,
      feature_types = [OutputType.CONTINUOUS] * (6)
      )
print("model training complete")
model.save(file_name_model)

loaded_model = DGAN(DGANConfig(
    max_sequence_len=timelength,
    sample_len=sample_len_,
    batch_size=batch_size_,
    epochs=epochs_, # For real data sets, 100–1000 epochs is typical
     feature_num_layers=num_layers_,
     attribute_discriminator_learning_rate = adlr_,
    feature_num_units = num_units_ ,
    generator_learning_rate = glr_ ,
        discriminator_learning_rate= dlr_,
))

loaded_model.load(file_name=file_name_model)

synthetic_df = loaded_model.generate_numpy(1)

attributes_gen =synthetic_df[0]
features_gen = synthetic_df[1]
```

Got the below error 
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-20-02dfe40d3ef9>](https://localhost:8080/#) in <module>
     13 loaded_model.load(file_name=file_name_model)
     14 
---> 15 synthetic_df = loaded_model.generate_numpy(1)
     16 
     17 attributes_gen =synthetic_df[0]

[/usr/local/lib/python3.8/dist-packages/gretel_synthetics/timeseries_dgan/dgan.py](https://localhost:8080/#) in generate_numpy(self, n, attribute_noise, feature_noise)
    434                 internal_data_list.append(
    435                     self._generate(
--> 436                         self.attribute_noise_func(self.config.batch_size),
    437                         self.feature_noise_func(self.config.batch_size),
    438                     )

AttributeError: 'DGAN' object has no attribute 'attribute_noise_func'
```

**Comment by AravAct** [comment]
loading DGAN directly worked perfectly. I can load the saved model and generate data again. Thanks for the clarification. Closing this.
