### ISSUE TITLE
[BUG] example notebook error

### ISSUE THREAD

**Issue by opyate** [gretelai/gretel-synthetics#157]
**What version of synthetics are you using?**

0.21.0

**What would you like to see / What problem are you having?**

I created a new project, fresh conda environment with `python==3.9.16`

Then I copied this notebook:
https://github.com/gretelai/gretel-synthetics/blob/master/examples/synthetic_records.ipynb

And as per the notebook instructions, installed only:

- `gretel-synthetics[tf]`
- `jupyter`

It fails on the "train a model" (i.e. second code cell) with:

> ImportError: cannot import name 'range_op' from 'tensorflow.python.data.ops' 

Perhaps the insutrctions in the notebook is at odds with the instruction in the [script](https://github.com/gretelai/gretel-synthetics/blob/master/setup-utils/setup-gretel-synthetics-tensorflow28-with-gpu.sh#L38) which recommends `tensorflow==2.8`.

I tried installing `tensorflow==2.8` in addition to the aforementioned `gretel-synthetics[tf]` and `jupyter`, but this time running the first cell fails with:

> ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.11; Detected an installation of version 2.8.0. Please upgrade TensorFlow to proceed.

**Comment by opyate** [comment]
I've started over with a fresh conda environment, then run:

```
pip install 'tensorflow==2.8'
pip install gretel-synthetics
pip install jupyter
```

And now the first cell fails with:

> ModuleNotFoundError: No module named 'tensorflow.python.checkpoint'

**Comment by johntmyers** [comment]
Hi, thanks for reporting this. This may be because we need to update our `setup.py` and the other install script you referenced. Can you try doing a `pip install -U tensorflow==2.11` and try with that version? That is working for me locally while testing.

**Comment by opyate** [comment]
> Can you try doing a pip install -U tensorflow==2.11 and try with that version? 

Thanks for the reply! That version is getting me further, thanks. Training now, on 3rd epoch.
