### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'gretel_helpers'

### ISSUE THREAD

**Issue by anurag-ae2024** [gretelai/gretel-synthetics#167]
**Are you reporting a bug or FR?**
 - [ ] Bug

**What version of synthetics are you using?**

0.20.0

**What would you like to see / What problem are you having?**

I'm unable to import gretel in my code. 
`from gretel_helpers.synthetics import create_df, SyntheticDataBundle` gives me import error.

**Are you using GPU or a CPU?**

CPU

**What environment are you working in?**

VSCode

**What version of python are you using?**

3.10.14

**Please provide any tracebacks or error messages you are receiving**

```
 from gretel_helpers.synthetics import create_df, SyntheticDataBundle
ModuleNotFoundError: No module named 'gretel_helpers'
```

**Comment by johntmyers** [comment]
Hi,

The example code you shared is not part of this library. Please see the examples here: https://github.com/gretelai/gretel-synthetics/tree/master/examples

Can you please share what example code you were referencing?
