### ISSUE TITLE
Elaborate inner works of the modelling

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [gretelai/gretel-synthetics#17]
Hi, Nice work! Really nice blogpost and repo. Since this is an area of interest of mine, I was wondering if you could elaborate a bit on some aspects. 

As far as I see, as encoding for the data you are using some form of sentencepiece, which I interpret as that you encode each table cell as a token for the encoder. Then, in the model, this token is mapped to a single embedding layer for all information. Correct?

How is training done? Does it just try to predict the next token at each timestep (also for each row)?

Now, i'm not extremely familiar with differential privacy, but I think its very nice that you have that built-in. My questions would be that since also continuous values are encoded as tokens, is there not a high chance of getting duplicate rows as in the train set? Specifically with smaller datasets like the Heart Disease dataset you use in the blogpost. And with these small datasets, do you see a large difference in results between training with and without dp? 

Lastly, how do you evaluate the similarity between your real and fake data? Did you do in depth analysis of why the results of some of these classifiers were higher?

**Comment by zredlined** [comment]
Thanks! I'll try to answer your questions below.

Sentencepiece learns a vocabulary from the raw text, not necessarily per cell. From there each token ID (integer) is mapped to the embedding layer in the neural network.

See the `split_input_target` function in train.py to see how the training set is created from source data. 

With differential privacy enabled, the model will not memorize and replay a unique row in the dataset. We also rarely see rows being repeated from the training data even without DP if the model is not overfit. For a good paper on this topic, check out "The Secret Sharer: Evaluating and Testing Unintended Memorization in Neural Networks”.

Lastly, we are working to launch a service that helps users create and validate the quality of their synthetic data. In the meantime- here is a Medium post on some of the techniques we use: https://medium.com/gretel-ai/deep-dive-on-generating-synthetic-data-for-healthcare-41acb4078707
