### ISSUE TITLE
[HELP NEEDED] Credit card example

### ISSUE THREAD

**Issue by danielstankw** [gretelai/gretel-synthetics#171]
Hi,
I am running this example:
https://github.com/gretelai/gretel-synthetics/blob/master/examples/research/synthetics_knn_generate.ipynb

Because utilizing DataFramebatch doesnt work for me:
```py
batcher = DataFrameBatch(df=training_set, batch_size=32, config=config_template)
batcher.create_training_data()
batcher.train_all_batches()
```
I use
```
config = TensorFlowConfig(
    batch_size=512,
    input_data_path=saved_set_path,
    gen_lines=1000,
    dropout_rate=0.4,
    rnn_units=1024,
    learning_rate = 0.001,
    max_lines=1e5,
    checkpoint_dir=str(Path.cwd() / "checkpoints_synthetic"),
    field_delimiter=",",
    overwrite=True
)
tokenizer = CharTokenizerTrainer(config=config)
train(config, tokenizer)
```
Whenever I try to generate the text I get the following
```
GenText(valid=False, text='627417,1.0,1', explain='record is 3 columns, not 31 as expected', delimiter=',')
```
The model is able to generate just 3 columns instead of 31.
Why is that? How can I fix that?

My training results of the model are quite good, so it should be able to perform accordingly

```
loss: 0.2665 - accuracy: 0.9200 - val_loss: 0.2439 - val_accuracy: 0.9270
```

**Comment by danielstankw** [comment]
@zredlined

**Comment by Marjan-emd** [comment]
This notebook is working with one of our old models (LSTM) and requires `tensorflow==2.9.0` which will be updated accordingly.
We also recommend working with one of the Gretel's most recent models, Navigator Fine Tuning, from the [console](https://console.gretel.ai/login?redirect=https%3A%2F%2Fconsole.gretel.ai%2Fuse_cases%2Fcards%2Fuse-case-navigator-ft)/[SDK](https://colab.research.google.com/github/gretelai/gretel-blueprints/blob/main/docs/notebooks/demo/navigator-fine-tuning-intro-tutorial.ipynb).
