### ISSUE TITLE
SentencePiece data tokenization to improve model accuracy

### ISSUE THREAD

**Issue by zredlined** [gretelai/gretel-synthetics#2]
Add SentencePiece tokenizer to extend synthetics model from character-based encoding to support flexible token-based encoding, ideally training a tokenizer on raw input data. Versus a character-based encoding, this should be more efficient (grouping common characters into a single token), and result in better synthetic data creation (common spacing and character patterns learned by tokenizer).

See: subword units and byte-pair-encoding (BPE) [Sennrich et al.]) and unigram language model [Kudo])

Goals:
* Specify fixed vocabulary size for training (e.g. 100, 500, 1000)
* Specify minimum character coverage (0.0-1.0)
* Detokenize in a generalized, language and character set independent manner

**Comment by aehrath** [comment]
Somehow I am still on these notifications with my home email :)
