### ISSUE TITLE
Size Limits

### ISSUE THREAD

**Issue by zakraicik** [gretelai/gretel-synthetics#22]
Are there limits to the number of columns in the dataframe that can be passed to train_rnn?

If I run the code with just 5 columns it works, but fails if I pass all 1500 columns. Wondering where the limit is exactly and why it's there.

**Comment by zakraicik** [comment]
Yeah- just to quickly test the tool, I had borrowed the hyperparamters from the heart disease kaggle example. I'm not sure how to tune them yet. 

The code is below. 

`config = LocalConfig(
    max_lines=0, # read all lines (zero)
    epochs=15, # 15-30 epochs for production
    vocab_size=200, # tokenizer model vocabulary size
    character_coverage=1.0, # tokenizer model character coverage percent
    gen_chars=0, # the maximum number of characters possible per-generated line of text
    gen_lines=10000, # the number of generated text lines
    rnn_units=256, # dimensionality of LSTM output space
    batch_size=64, # batch size
    buffer_size=1000, # buffer size to shuffle the dataset
    dropout_rate=0.2, # fraction of the inputs to drop
    dp=True, # let's use differential privacy
    dp_learning_rate=0.015, # learning rate
    dp_noise_multiplier=1.1, # control how much noise is added to gradients
    dp_l2_norm_clip=1.0, # bound optimizer's sensitivity to individual training points
    dp_microbatches=256, # split batches into minibatches for parallelism
    checkpoint_dir=(Path.cwd() / 'checkpoints').as_posix(),
    save_all_checkpoints=False,
    field_delimiter=",",
    input_data_path=annotated_file # filepath or S3
)

train_rnn(config)`

The error I receive is 

> RuntimeError: Internal: /Users/travis/build/google/sentencepiece/src/trainer_interface.cc(336) [!sentences_.empty()] 

My DF is ~45K rows x 1500 columns. If I shrink the number of rows, I get the same error. However, if I shrink the number of columns it runs so I think the google sentence piece probably has a maximum text length.

**Comment by zakraicik** [comment]
@zredlined Unfortunately I can't provide any of the data. 

I'll try expanding the vocab size and get back to you.

**Comment by zakraicik** [comment]
Changing the vocab size doesn't help

**Comment by johntmyers** [comment]
@zakraicik After you output the DF to the training CSV, can you tell us what the strlen of a full row is on average? Maybe we can re-create by just generating a dataset that has similar dimensions.

**Comment by johntmyers** [comment]
I got it to error on a dummy set I made. We'll take a look.

**Comment by johntmyers** [comment]
Got it fixed, will cut a new release. You'll have to override the max line len. SP defaults to 2049. I generated lines that were 49500 in length. I had to set the size to > 50k still, so you'll want the max size you input to be a few K higher than your max line is.

**Comment by johntmyers** [comment]
@zakraicik Cutting v0.9.3 that should let you set a custom line limit that overrides SP's.
