### ISSUE TITLE
Data Storage

### ISSUE THREAD

**Issue by zakraicik** [gretelai/gretel-synthetics#24]
Hi - 

Can you confirm no data passed to gretel-synthetics is stored anywhere?

Thanks,
Zak

**Comment by johntmyers** [comment]
Yes, there are no implicit data transfers. Everything happens on the local system where the package is installed and imported from.

**Comment by johntmyers** [comment]
To be more clear, when you set the training data location, an annotated training set is created and stored on local disk. This is based on the checkpoint directory that you create. The only config object we have is `LocalConfig` so to answer most succinctly, data is stored, but only locally.

**Comment by zakraicik** [comment]
Thanks -  got it. I just wanted to make sure nothing was being sent to your servers behind the scenes.
