### ISSUE TITLE
Batch Size Question

### ISSUE THREAD

**Issue by zakraicik** [gretelai/gretel-synthetics#25]
Sorry for spamming the issues page. If there is a better way to communicate (slack, etc) let me know. 

As I've mentioned, my dataset is about 46K rows X 1500 columns. I have the batch size set at 64. Doesn't this mean the number of batches is 46k/64 = 718? How do I end up with the 17K batches? Screenshot below. 

<img width="796" alt="Screen Shot 2020-06-04 at 4 39 50 PM" src="https://user-images.githubusercontent.com/43297285/83808041-0c448d80-a682-11ea-88d4-e0b6c55959b1.png">

I attached the code below but it's the same as previous threads. 

```
config = LocalConfig(
    max_lines=0, # read all lines (zero)
    epochs=15, # 15-30 epochs for production
    vocab_size=2000, # tokenizer model vocabulary size
    character_coverage=1.0, # tokenizer model character coverage percent
    gen_chars=0, # the maximum number of characters possible per-generated line of text
    max_line_len=55000,  # the max line length SentencePiece will consider
    gen_lines=10000, # the number of generated text lines
    rnn_units=256, # dimensionality of LSTM output space
    batch_size=64, # batch size
    buffer_size=1000, # buffer size to shuffle the dataset
    dropout_rate=0.2, # fraction of the inputs to drop
    dp=True, # let's use differential privacy
    dp_learning_rate=0.015, # learning rate
    dp_noise_multiplier=1.1, # control how much noise is added to gradients
    dp_l2_norm_clip=1.0, # bound optimizer's sensitivity to individual training points
    dp_microbatches=256, # split batches into minibatches for parallelism
    checkpoint_dir=(Path.cwd() / 'checkpoints').as_posix(),
    save_all_checkpoints=False,
    field_delimiter=",",
    input_data_path=annotated_file # filepath or S3
)

train_rnn(config)
```

**Comment by johntmyers** [comment]
That's the number of steps per epoch. Each step is one batch size of the training data.

**Comment by zakraicik** [comment]
Is the number of steps different than the 45k/64 = 718 I have written above?

**Comment by zredlined** [comment]
@zakraicik- the input text gets tokenized into variable length sentence pieces. You have 45k rows and 1500 columns, but the characters in each row will get tokenized into variable-length sentence pieces. Each piece gets mapped to an integer id that is batched into groups of 64 for training.
