### ISSUE TITLE
Duplicates present in Unique columns

### ISSUE THREAD

**Issue by Satishkumar44** [gretelai/gretel-synthetics#77]
Hi I have used template generating synthetic data from your own csv. I have given input as 1000 records and output also 1000
attached the input and output. In the output the column ref_id is primary key however it is generating some duplicates. Is there any configuration to be set so that it will generate unique values in primary key columns.
[file.zip](https://github.com/gretelai/gretel-synthetics/files/5660093/file.zip)

**Comment by johntmyers** [comment]
Hi @Satishkumar44 you can actually preserve certain columns and use them as seeds for generating the rest of the record so you get exactly 1000 records with the same PKs. Here's some modifications you can do:

Just after you create the `config_template` and before you create the `SyntheticDataBundle` you can extract out a list of dictionaries that represent "seed" values for each record.

Also here, I replicated the training data 5 times, which is optional, but in this case helped generate results faster:

```python
import json

seed_data = json.loads(training_df[["REF_ID"]].to_json(orient="records"))
training_df = pd.concat([training_df] * 5).sample(frac=1)
```

When you create the `SyntheticDataBundle` you specify which columns you want to preserve as seed fields using the `header_prefix=["REF_ID"]` param

![image](https://user-images.githubusercontent.com/9696606/101507139-3bdf9580-3944-11eb-9e58-609be13b463b.png)


When you go to generate data, you can feed the list of seed fields in. The model will generate one record for each seed in the list:

```python
bundle.generate(num_lines=nrows, max_invalid=nrows, seed_fields=seed_data, num_proc=1)
```

Please note that `num_proc=1` must be set here, as only one CPU can currently be used for seed based generation.

I tested this and attached my results.
[synthetic.csv.zip](https://github.com/gretelai/gretel-synthetics/files/5660316/synthetic.csv.zip)

**Comment by Satishkumar44** [comment]
while runing the bundle.generate() facing the below error . Can you help me out.
![generating](https://user-images.githubusercontent.com/60460487/101605192-e67cb480-3a27-11eb-9895-a505d317e965.PNG)

**Comment by johntmyers** [comment]
Please share more detail. If you can share the full Notebook. The error means you have too many seed fields specified and you should only have one based on what I provided above.

**Comment by Satishkumar44** [comment]
I have shared my notebook the data is same as shared before
[Synthetic Data Generation.zip](https://github.com/gretelai/gretel-synthetics/files/5665876/Synthetic.Data.Generation.zip)

**Comment by johntmyers** [comment]
This looks like a slightly older version of `gretel-synthetics` is running. Can you re-install that so you are at version 0.15.2?

**Comment by Satishkumar44** [comment]
Yes after upgrading to 0.15.2 it works fine, But my issue is when iam trying to generate 2000 rows from the same data without preserving the primary key it is generating data duplicates in primary key column(REF_ID).Is there any way that primary key columns will not contain duplicates.

**Comment by johntmyers** [comment]
There's currently no way to avoid duplicates unless you specifically provide a list of seeds like demonstrated above. Otherwise you can drop the primary key column, generate records, and add the primary key values back in.

**Comment by Satishkumar44** [comment]
Thankyou for your support
