### ISSUE TITLE
gretel not finding GPU

### ISSUE THREAD

**Issue by tmontana** [gretelai/gretel-synthetics#80]
Hi.  I've been trying to run the examples but I keep getting a warning that the GPU is not found.  !nvidia-smi does show the GPU however.  This is all a fresh install within a conda environment.  

conda create --name gretel --python=3.8
conda activate gretel
pip install gretel-synthetics[tf] 

![image](https://user-images.githubusercontent.com/18288458/104851525-cc22da00-58f5-11eb-89b4-6ad67bcefbab.png)

![image](https://user-images.githubusercontent.com/18288458/104851550-e1980400-58f5-11eb-93d9-282a2fca610c.png)

Thanks for the help,

**Comment by johntmyers** [comment]
If you import TF yourself whats your output from:


physical_devices = tf.config.list_physical_devices('GPU')
print("Num GPUs:", len(physical_devices))

and also

tf.test.gpu_device_name()

**Comment by tmontana** [comment]
Here is the output:

physical_devices = tf.config.list_physical_devices('GPU')
print("Num GPUs:", len(physical_devices))

Num GPUs: 1

tf.test.gpu_device_name()

'/device:GPU:0'

> If you import TF yourself whats your output from:
> 
> ```
> physical_devices = tf.config.list_physical_devices('GPU')
> print("Num GPUs:", len(physical_devices))
> ```
> 
Num GPUs: 1


> and also
> 
> ```
> tf.test.gpu_device_name()
> ```

'/device:GPU:0'


thanks

**Comment by johntmyers** [comment]
Thanks, did you run this in the example notebook that you were trying to run or somewhere else?

Also, that warning doesn't change anything under the hood, it just prints the warning in the event the `tf.test.gpu_device_name()` does not return the expected value.  The model should still start to train regardless. If you let the model train, how long does each epoch take to run?

**Comment by tmontana** [comment]
> Thanks, did you run this in the example notebook that you were trying to run or somewhere else?
> 
> Also, that warning doesn't change anything under the hood, it just prints the warning in the event the `tf.test.gpu_device_name()` does not return the expected value. The model should still start to train regardless. If you let the model train, how long does each epoch take to run?

Ok my bad - for some reason the problem is linked to my conda environment.  I had run your commands in the Python3 environment.  If I run them in the Gretel environment (created as above) I get 'Num GPUs: 0'.

Would you know why TF is not seeing the GPU?

Thanks

**Comment by johntmyers** [comment]
I'm not sure, I've personally only used a `virtualenv` to run things. @zredlined have you run into this with conda or had to do any other steps to allow the GPU to be accessed in an environment like that?

**Comment by zredlined** [comment]
Tensorflow versions are coded to different CUDA library versions. Conda's pretty good at handling this- so we usually recommend setting up tensorflow through Conda. 

Here's a link to the pinned [TF->CUDA](https://cdn-images-1.medium.com/max/1000/1*pyZAEgX30F09Fgt9jksB-Q.png) versions. 

Try installing dependencies with Conda. 

`conda install tensorflow=2.3 cudatoolkit=10.1`
`pip install gretel-synthetics`

**Comment by tmontana** [comment]
still doesn't work.  Anyway it's a tensorflow issue apparently (and not Gretel) as the GPU is not recognized after I install just tensorflow.  I'll investigate it further.  Thank you

**Comment by zredlined** [comment]
Looks like there might be some dependency mismatches in the latest Conda scripts. Here are instructions for building a `tensorflow==2.4` virtual environment with Conda, gretel-synthetics, and GPU. I tested on AWS running a debian image. Hope this helps! 

First, setup your Conda environment
`conda create --name tf --python=3.8`
`conda activate tf`

Copy this Gist using the TensorFlow team's latest [instructions](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_110) into a shell script named `setup_deps.sh`: https://gist.github.com/zredlined/dc7a0cb5ca72d58a8cc29ce6eee441cf

Next, run the setup script
sh `setup_deps.sh`

**Comment by tmontana** [comment]
> sh `setup_deps.sh`

thanks @zredlined - that worked.  I've been on it for the past 3 hours and was going to give up.  I tested on AzureML and working fine.  Cheers
