### ISSUE TITLE
Question on continuous values

### ISSUE THREAD

**Issue by tmontana** [gretelai/gretel-synthetics#81]
Hi.  I'm wondering how Gretel deals with continuous values in the input data. I can see how categorical values can be similar to words in a text but what about continuous ones?

Thanks

**Comment by johntmyers** [comment]
@tmontana when you say continuous do you mean monotonic (like increasing / decreasing values i.e. timestamps, counters, etc) or values that exist in set ranges like an age, etc.?

**Comment by tmontana** [comment]
I mean a column containing any real valued number:  0.99836655477 as a random float example.

**Comment by amysteier** [comment]
During training, the fields in a record of input data are all first parsed into a series of tokens. The parsing is somewhat agnostic as to whether a particular field value is numeric or categorical. Tokens can be either character n-grams or word/number n-grams. A number like 352.4 may end up being one token (352.4), or two tokens (352 and .4) or potentially even more tokens. The chance of a string of characters becoming a token has to do with the probability of that string occurring in the training set.
When generating, the next token is always predicted based on the previous tokens predicted by the model. One of the tokens that can be predicted is the field delimiter (usually something like ",").  Again, the model is agnostic as to whether the combined tokens between two field delimiters is numeric or not. The process works quite well for continuous values. It synthesizes an all new series of values for a continuous field, with the same distribution and range as the original series, yet note exactly the same numbers.

**Comment by amysteier** [comment]
Additionally, it's worth noting that if your float values have an extremely high precision (as in your example), and all you really care about is a precision like .9983, then you're better off first truncating your floats before you do the training.  The model has an easier learning task and will end up doing a better job when synthesizing.

**Comment by tmontana** [comment]
Thanks for the detailed explanation.  The precision issue makes sense as well.
